# Generated by Django 3.2.24 on 2024-04-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api_app', '0002_auto_20240402_1348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFeed',
            new_name='ProfileFeedItem',
        ),
    ]
